In [47]:
# X data will be all columns and y data will be player 1 buttons
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

<h1>Dataset 1</h1>

In [48]:
df = pd.read_csv('dataset.csv')
df

timer fight_result  has_round_started  is_round_over  Player1_ID  \
0         153     NOT_OVER              False          False           5   
1         153     NOT_OVER              False          False           5   
2         153     NOT_OVER              False          False           5   
3         153     NOT_OVER              False          False           5   
4         153     NOT_OVER              False          False           5   
...       ...          ...                ...            ...         ...   
121593     64     NOT_OVER               True          False           7   
121594     64     NOT_OVER               True          False           7   
121595     64     NOT_OVER               True          False           7   
121596     64     NOT_OVER               True          False           7   
121597     64     NOT_OVER               True          False           7   

        Player1_health  Player1_x_coord  Player1_y_coord  Player1_is_jumping  \
0                  176              205              192               False   
1                  176              205              192               False   
2                  176              205              192               False   
3                  176              205              192               False   
4                  176              205              192               False   
...                ...              ...              ...                 ...   
121593               0             1919                0               False   
121594               0             1919                0               False   
121595               0             1919                0               False   
121596               0             1919                0               False   
121597               0             1919                0               False   

        Player1_is_crouching  ...  player2_buttons_up  player2_buttons_down  \
0                      False  ...               False                 False   
1                      False  ...               False                 False   
2                      False  ...               False                 False   
3                      False  ...               False                 False   
4                      False  ...               False                 False   
...                      ...  ...                 ...                   ...   
121593                 False  ...               False                 False   
121594                 False  ...               False                 False   
121595                 False  ...               False                 False   
121596                 False  ...               False                 False   
121597                 False  ...               False                 False   

        player2_buttons_right  player2_buttons_left  player2_buttons_Y  \
0                       False                 False              False   
1                       False                 False              False   
2                       False                 False              False   
3                       False                 False              False   
4                       False                 False              False   
...                       ...                   ...                ...   
121593                  False                 False              False   
121594                  False                 False              False   
121595                  False                 False              False   
121596                  False                 False              False   
121597                  False                 False              False   

        player2_buttons_B  player2_buttons_X  player2_buttons_A  \
0                   False              False              False   
1                   False              False              False   
2                   False              False              False   
3                   False   

In [49]:
# Function to put player1 buttons into a list
def player1_buttons():
    y_data = []
    for index, row in df.iterrows():
        selected_values = row[['player1_buttons_up', 'player1_buttons_down', 'player1_buttons_right', 'player1_buttons_left', 'player1_buttons_Y', 'player1_buttons_B', 'player1_buttons_X', 'player1_buttons_A', 'player1_buttons_L', 'player1_buttons_R']].tolist()
        y_data.append(selected_values)
    return y_data


In [50]:
y = player1_buttons()

In [51]:
y = np.array(y)

In [52]:
y

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [ True, False,  True, ..., False, False, False],
       ...,
       [False,  True, False, ..., False, False, False],
       [False,  True, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [53]:
df.drop(['player1_buttons_up', 'player1_buttons_down', 'player1_buttons_right', 'player1_buttons_left', 'player1_buttons_Y', 'player1_buttons_B', 'player1_buttons_X', 'player1_buttons_A', 'player1_buttons_L', 'player1_buttons_R'], axis=1, inplace=True)

In [54]:
# Convert fight_result to 0(NOT_OVER), 1(P1) or -1(P2)
df['fight_result'] = df['fight_result'].map({'NOT_OVER': 0, 'P1': 1, 'P2': -1})

In [55]:
df

timer  fight_result  has_round_started  is_round_over  Player1_ID  \
0         153             0              False          False           5   
1         153             0              False          False           5   
2         153             0              False          False           5   
3         153             0              False          False           5   
4         153             0              False          False           5   
...       ...           ...                ...            ...         ...   
121593     64             0               True          False           7   
121594     64             0               True          False           7   
121595     64             0               True          False           7   
121596     64             0               True          False           7   
121597     64             0               True          False           7   

        Player1_health  Player1_x_coord  Player1_y_coord  Player1_is_jumping  \
0                  176              205              192               False   
1                  176              205              192               False   
2                  176              205              192               False   
3                  176              205              192               False   
4                  176              205              192               False   
...                ...              ...              ...                 ...   
121593               0             1919                0               False   
121594               0             1919                0               False   
121595               0             1919                0               False   
121596               0             1919                0               False   
121597               0             1919                0               False   

        Player1_is_crouching  ...  player2_buttons_up  player2_buttons_down  \
0                      False  ...               False                 False   
1                      False  ...               False                 False   
2                      False  ...               False                 False   
3                      False  ...               False                 False   
4                      False  ...               False                 False   
...                      ...  ...                 ...                   ...   
121593                 False  ...               False                 False   
121594                 False  ...               False                 False   
121595                 False  ...               False                 False   
121596                 False  ...               False                 False   
121597                 False  ...               False                 False   

        player2_buttons_right  player2_buttons_left  player2_buttons_Y  \
0                       False                 False              False   
1                       False                 False              False   
2                       False                 False              False   
3                       False                 False              False   
4                       False                 False              False   
...                       ...                   ...                ...   
121593                  False                 False              False   
121594                  False                 False              False   
121595                  False                 False              False   
121596                  False                 False              False   
121597                  False                 False              False   

        player2_buttons_B  player2_buttons_X  player2_buttons_A  \
0                   False              False              False   
1                   False              False              False   
2                   False              False              False   
3               

In [56]:
# Function to put all columns into a list except those in y_data
def x_data():
    x_data = []
    for index, row in df.iterrows():
        x_data.append(row.tolist())
    return x_data

In [57]:
X = x_data()
X = np.array(X)

In [58]:
X

array([[153,   0,   0, ...,   0,   0,   0],
       [153,   0,   0, ...,   0,   0,   0],
       [153,   0,   0, ...,   0,   0,   0],
       ...,
       [ 64,   0,   1, ...,   0,   0,   0],
       [ 64,   0,   1, ...,   0,   0,   0],
       [ 64,   0,   1, ...,   0,   0,   0]])

In [59]:
# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

<h3>Decision Tree Classifier</h3>

In [60]:
from sklearn.tree import DecisionTreeClassifier

In [61]:
decisionTree = DecisionTreeClassifier()
decisionTree.fit(X_train, y_train)

DecisionTreeClassifier()

In [62]:
decisionTree.score(X_test, y_test)

0.3399259868421053

In [63]:
decisionTree.predict(X_test)

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [64]:
y_test

array([[False, False, False, ..., False, False, False],
       [False,  True,  True, ..., False, False, False],
       [False,  True, False, ..., False, False, False],
       ...,
       [False,  True, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False,  True, ..., False, False, False]])

In [65]:
# Importing required libraries
import joblib

# Saving the trained model as a file
joblib.dump(decisionTree, "decision_tree_model.pkl")

['decision_tree_model.pkl']

<h3>Decision Tree Regressor</h3>

In [66]:
from sklearn.tree import DecisionTreeRegressor

In [67]:
decisionTreeRegressor = DecisionTreeRegressor()
decisionTreeRegressor.fit(X_train, y_train)

DecisionTreeRegressor()

In [68]:
decisionTreeRegressor.score(X_test, y_test)

-0.1152928081845137

In [69]:
decisionTreeRegressor.predict(X_test)

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.16666667, 0.16666667, 0.16666667, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [70]:
y_test

array([[False, False, False, ..., False, False, False],
       [False,  True,  True, ..., False, False, False],
       [False,  True, False, ..., False, False, False],
       ...,
       [False,  True, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False,  True, ..., False, False, False]])

In [71]:
# Importing required libraries
import joblib

# Saving the trained model as a file
joblib.dump(decisionTreeRegressor, "decision_tree_regressor.pkl")

['decision_tree_regressor.pkl']

<h3>Forest Regressor</h3>

In [72]:
from sklearn.ensemble import RandomForestRegressor

In [78]:
randomForest = RandomForestRegressor(max_depth=2, random_state=0, n_estimators=50)
randomForest.fit(X_train, y_train)

RandomForestRegressor(max_depth=2, n_estimators=50, random_state=0)

In [79]:
randomForest.score(X_test, y_test)

0.306894648179585

In [80]:
randomForest.predict(X_test)

array([[0.04563455, 0.2654444 , 0.21509978, ..., 0.        , 0.        ,
        0.01422129],
       [0.03439065, 0.28299148, 0.18959613, ..., 0.        , 0.        ,
        0.02850538],
       [0.04563455, 0.2654444 , 0.21509978, ..., 0.        , 0.        ,
        0.01422129],
       ...,
       [0.03439065, 0.28299148, 0.18959613, ..., 0.        , 0.        ,
        0.02850538],
       [0.04563455, 0.2654444 , 0.21509978, ..., 0.        , 0.        ,
        0.01422129],
       [0.04563455, 0.2654444 , 0.21509978, ..., 0.        , 0.        ,
        0.01422129]])

In [81]:
y_test

array([[False, False, False, ..., False, False, False],
       [False,  True,  True, ..., False, False, False],
       [False,  True, False, ..., False, False, False],
       ...,
       [False,  True, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False,  True, ..., False, False, False]])

In [82]:
# Importing required libraries
import joblib

# Saving the trained model as a file
joblib.dump(randomForest, "random_forest.pkl")

['random_forest.pkl']

<h1>Dataset 2</h1>

In [49]:
df = pd.read_csv('dataset_2.csv')
df

p1_player_id  p1_health  p1_is_crouching  p1_is_jumping  \
0                 0        176            False          False   
1                 0        176            False          False   
2                 0        176            False          False   
3                 0        176            False          False   
4                 0        176            False          False   
...             ...        ...              ...            ...   
70520             7        116             True          False   
70521             7        116             True          False   
70522             7        116             True          False   
70523             7        116             True          False   
70524             7        116             True          False   

       p1_is_player_in_move  p1_move_id  p1_x_coord  p1_y_coord  p1_up  \
0                     False           0         205         192  False   
1                     False           0         205         192  False   
2                     False           0         205         192  False   
3                     False           0         205         192  False   
4                     False           0         205         192  False   
...                     ...         ...         ...         ...    ...   
70520                  True    33554433         303         192  False   
70521                  True    33554433         203         192   True   
70522                  True    33554433         344         192  False   
70523                  True    33554433         203         192  False   
70524                  True    33554433         203         192  False   

       p1_down  ...   p2_Y   p2_B   p2_X   p2_A   p2_L   p2_R  timer  \
0        False  ...  False  False  False  False  False  False    153   
1        False  ...  False  False  False  False  False  False    153   
2        False  ...  False  False  False  False  False  False    153   
3         True  ...  False  False  False  False  False  False    153   
4        False  ...  False  False  False  False  False  False    153   
...        ...  ...    ...    ...    ...    ...    ...    ...    ...   
70520    False  ...  False  False  False  False  False  False     55   
70521    False  ...  False  False  False  False  False  False     55   
70522    False  ...  False  False  False  False  False  False     55   
70523    False  ...  False  False  False  False  False  False     54   
70524    False  ...  False  False  False  False  False  False     54   

       fight_result  has_round_started  is_round_over  
0          NOT_OVER              False          False  
1          NOT_OVER              False          False  
2          NOT_OVER              False          False  
3          NOT_OVER              False          False  
4          NOT_OVER              False          False  
...             ...                ...            ...  
70520      NOT_OVER               True          False  
70521      NOT_OVER               True          False  
70522      NOT_OVER               True          False  
70523      NOT_OVER               True          False  
70524            P1               True           True  

[70525 rows x 44 columns]

In [50]:
df.columns

Index(['p1_player_id', 'p1_health', 'p1_is_crouching', 'p1_is_jumping',
       'p1_is_player_in_move', 'p1_move_id', 'p1_x_coord', 'p1_y_coord',
       'p1_up', 'p1_down', 'p1_right', 'p1_left', 'p1_select', 'p1_start',
       'p1_Y', 'p1_B', 'p1_X', 'p1_A', 'p1_L', 'p1_R', 'p2_player_id',
       'p2_health', 'p2_is_crouching', 'p2_is_jumping', 'p2_is_player_in_move',
       'p2_move_id', 'p2_x_coord', 'p2_y_coord', 'p2_up', 'p2_down',
       'p2_right', 'p2_left', 'p2_select', 'p2_start', 'p2_Y', 'p2_B', 'p2_X',
       'p2_A', 'p2_L', 'p2_R', 'timer', 'fight_result', 'has_round_started',
       'is_round_over'],
      dtype='object')

In [51]:
# Function to put player1 buttons into a list
def player1_buttons_2():
    y_data = []
    for index, row in df.iterrows():
        selected_values = row[['p1_up', 'p1_down', 'p1_right', 'p1_left', 'p1_Y', 'p1_B', 'p1_X', 'p1_A', 'p1_L', 'p1_R']].tolist()
        y_data.append(selected_values)
    return y_data

In [52]:
y = player1_buttons_2()
y = np.array(y)
y

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False,  True, ..., False, False, False],
       ...,
       [False, False,  True, ..., False, False, False],
       [False, False,  True, ..., False, False, False],
       [False, False,  True, ..., False, False, False]])

In [53]:
df.drop(['p1_up', 'p1_down', 'p1_right', 'p1_left', 'p1_Y', 'p1_B', 'p1_X', 'p1_A', 'p1_L', 'p1_R', 'p1_start', 'p1_select'], axis=1, inplace=True)

In [54]:
# Convert fight_result to 0(NOT_OVER), 1(P1) or -1(P2)
df['fight_result'] = df['fight_result'].map({'NOT_OVER': 0, 'P1': 1, 'P2': -1})

In [55]:
df

p1_player_id  p1_health  p1_is_crouching  p1_is_jumping  \
0                 0        176            False          False   
1                 0        176            False          False   
2                 0        176            False          False   
3                 0        176            False          False   
4                 0        176            False          False   
...             ...        ...              ...            ...   
70520             7        116             True          False   
70521             7        116             True          False   
70522             7        116             True          False   
70523             7        116             True          False   
70524             7        116             True          False   

       p1_is_player_in_move  p1_move_id  p1_x_coord  p1_y_coord  p2_player_id  \
0                     False           0         205         192             6   
1                     False           0         205         192             6   
2                     False           0         205         192             6   
3                     False           0         205         192             6   
4                     False           0         205         192             6   
...                     ...         ...         ...         ...           ...   
70520                  True    33554433         303         192             3   
70521                  True    33554433         203         192             3   
70522                  True    33554433         344         192             3   
70523                  True    33554433         203         192             3   
70524                  True    33554433         203         192             3   

       p2_health  ...   p2_Y   p2_B   p2_X   p2_A   p2_L   p2_R  timer  \
0            176  ...  False  False  False  False  False  False    153   
1            176  ...  False  False  False  False  False  False    153   
2            176  ...  False  False  False  False  False  False    153   
3            176  ...  False  False  False  False  False  False    153   
4            176  ...  False  False  False  False  False  False    153   
...          ...  ...    ...    ...    ...    ...    ...    ...    ...   
70520         18  ...  False  False  False  False  False  False     55   
70521         18  ...  False  False  False  False  False  False     55   
70522         18  ...  False  False  False  False  False  False     55   
70523         18  ...  False  False  False  False  False  False     54   
70524        255  ...  False  False  False  False  False  False     54   

       fight_result  has_round_started  is_round_over  
0                 0              False          False  
1                 0              False          False  
2                 0              False          False  
3                 0              False          False  
4                 0              False          False  
...             ...                ...            ...  
70520             0               True          False  
70521             0               True          False  
70522             0               True          False  
70523             0               True          False  
70524             1               True           True  

[70525 rows x 32 columns]

In [56]:
def x_data_2():
    x_data = []
    for index, row in df.iterrows():
        x_data.append(row.tolist())
    return x_data

In [57]:
X = x_data_2()
X = np.array(X)
X

array([[  0, 176,   0, ...,   0,   0,   0],
       [  0, 176,   0, ...,   0,   0,   0],
       [  0, 176,   0, ...,   0,   0,   0],
       ...,
       [  7, 116,   1, ...,   0,   1,   0],
       [  7, 116,   1, ...,   0,   1,   0],
       [  7, 116,   1, ...,   1,   1,   1]])

In [58]:
# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

<h3>Decision Tree</h3>

In [59]:
from sklearn.tree import DecisionTreeClassifier

In [63]:
decisionTree2 = DecisionTreeClassifier()

In [64]:
decisionTree2.fit(X_train, y_train)
decisionTree2.score(X_test, y_test)

0.32988302020560084

In [65]:
decisionTree2.predict(X_test)

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False,  True,  True, ..., False, False, False],
       [False, False,  True, ..., False, False, False],
       [False, False,  True, ..., False, False, False]])

In [67]:
y_test

array([[False,  True, False, ..., False, False, False],
       [False, False,  True, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False,  True,  True, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [68]:
# Importing required libraries
import joblib

# Saving the trained model as a file
joblib.dump(decisionTree2, "decision_tree_model_2.pkl")

['decision_tree_model_2.pkl']